extension=/usr/lib/newrelic-php5/agent/x64/newrelic-20160303.so
[newrelic]
newrelic.enabled = true
newrelic.license = "LICENSE_KEY"
newrelic.logfile = "/var/log/newrelic/php_agent.log"
newrelic.appname = "APP_NAME"
newrelic.daemon.logfile = "/var/log/newrelic/newrelic-daemon.log"
newrelic.daemon.port = /run/newrelic.sock
newrelic.daemon.ssl = true
newrelic.capture_params = false
newrelic.error_collector.enable = true
newrelic.error_collector.record_database_errors = true
newrelic.error_collector.prioritize_api_errors = false
newrelic.browser_monitoring.auto_instrument = true
newrelic.transaction_tracer.enable = true
newrelic.transaction_tracer.slow_sql = true
newrelic.webtransaction.name.remove_trailing_path = false
newrelic.cross_application_tracer.enabled = true
newrelic.high_security = false
